---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      gitHub-actions:
        patterns:
          - "*"

  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: monthly
    groups:
      devcontainers:
        patterns:
          - "*"
